import {
    DashboardOutlined,
    FlagOutlined,
    LinkOutlined,
    BarChartOutlined,
    TrophyOutlined,
    HeartOutlined,
    TeamOutlined,
    UserOutlined,
    SettingOutlined,
    SafetyOutlined,
    PlusOutlined,
    EditOutlined,
    DeleteOutlined,
    EyeOutlined,
    ShareAltOutlined,
    CopyOutlined,
    CheckOutlined,
    CloseOutlined,
    SearchOutlined,
    FilterOutlined,
    DownloadOutlined,
    UploadOutlined,
    ReloadOutlined,
    LogoutOutlined,
    LoginOutlined,
    BellOutlined,
    StarOutlined,
    FireOutlined,
    ThunderboltOutlined,
    RocketOutlined,
    ClockCircleOutlined,
    CalendarOutlined,
    MailOutlined,
    LockOutlined,
    UnlockOutlined,
    GlobalOutlined,
    ArrowUpOutlined,
    ArrowDownOutlined,
    ArrowRightOutlined,
    MenuOutlined,
    LeftOutlined,
    RightOutlined,
    PlayCircleOutlined,
    FileImageOutlined,
    MessageOutlined,
    WalletOutlined,
    DollarOutlined,
    ApartmentOutlined,
    BankOutlined,
    InfoCircleOutlined,
    WarningOutlined,
    CheckCircleOutlined,
    SunOutlined,
    MoonOutlined,
} from "@ant-design/icons";

export const ICONS = {
    // Navigation
    dashboard: DashboardOutlined,
    campaigns: FlagOutlined,
    links: LinkOutlined,
    analytics: BarChartOutlined,
    leaderboard: TrophyOutlined,
    donations: HeartOutlined,
    team: TeamOutlined,
    users: UserOutlined,
    settings: SettingOutlined,
    trust: SafetyOutlined,

    // Actions
    add: PlusOutlined,
    edit: EditOutlined,
    delete: DeleteOutlined,
    view: EyeOutlined,
    share: ShareAltOutlined,
    copy: CopyOutlined,
    check: CheckOutlined,
    close: CloseOutlined,
    search: SearchOutlined,
    filter: FilterOutlined,
    download: DownloadOutlined,
    upload: UploadOutlined,
    refresh: ReloadOutlined,
    logout: LogoutOutlined,
    login: LoginOutlined,

    // Status / Indicators
    bell: BellOutlined,
    star: StarOutlined,
    fire: FireOutlined,
    thunder: ThunderboltOutlined,
    rocket: RocketOutlined,
    clock: ClockCircleOutlined,
    calendar: CalendarOutlined,
    mail: MailOutlined,
    lock: LockOutlined,
    unlock: UnlockOutlined,
    global: GlobalOutlined,
    info: InfoCircleOutlined,
    warning: WarningOutlined,
    success: CheckCircleOutlined,

    // Directional
    arrowUp: ArrowUpOutlined,
    arrowDown: ArrowDownOutlined,
    arrowRight: ArrowRightOutlined,
    menu: MenuOutlined,
    left: LeftOutlined,
    right: RightOutlined,

    // Media
    play: PlayCircleOutlined,
    image: FileImageOutlined,
    message: MessageOutlined,

    // Finance
    wallet: WalletOutlined,
    dollar: DollarOutlined,

    // Org
    department: ApartmentOutlined,
    campus: BankOutlined,

    // Aliases
    trend: ArrowUpOutlined,
    user: UserOutlined,
    trophy: TrophyOutlined,

    // Theme
    sun: SunOutlined,
    moon: MoonOutlined,
} as const;

export type IconKey = keyof typeof ICONS;
