export const RANK_LEVELS: RankLevel[] = [
    {
        level: 1,
        name: "Seed",
        minScore: 0,
        badge: "🌱",
        color: "#6B7280",
        perks: ["Access to all active campaigns", "Personal smart link generation"],
    },
    {
        level: 2,
        name: "Sprout",
        minScore: 50,
        badge: "🌿",
        color: "#10B981",
        perks: ["Profile featured on campaign page", "Priority smart link analytics"],
    },
    {
        level: 3,
        name: "Branch",
        minScore: 150,
        badge: "🌳",
        color: "#3B82F6",
        perks: ["Leaderboard spotlight badge", "Team creation access"],
    },
    {
        level: 4,
        name: "Harvest",
        minScore: 350,
        badge: "🌾",
        color: "#F59E0B",
        perks: ["Exclusive reward drops", "Early campaign access"],
    },
    {
        level: 5,
        name: "Champion",
        minScore: 700,
        badge: "🏆",
        color: "#8B5CF6",
        perks: ["DMHicc Champion title", "Direct admin recognition", "Hall of fame entry"],
    },
    {
        level: 6,
        name: "Legend",
        minScore: 1500,
        badge: "⚡",
        color: "#EC4899",
        perks: ["All Champion perks", "Co-host on campaign launches", "Annual leadership award eligibility"],
    },
];
