export const RANK_LEVELS: RankLevel[] = [
    {
        level: 1,
        name: "Recruit",
        minScore: 0,
        badge: "🪖",
        color: "#6B7280",
        perks: ["Access to all active missions", "Personal ammunition generation"],
    },
    {
        level: 2,
        name: "Private",
        minScore: 50,
        badge: "🎖️",
        color: "#10B981",
        perks: ["Profile featured on mission page", "Priority ammunition analytics"],
    },
    {
        level: 3,
        name: "Corporal",
        minScore: 150,
        badge: "⚔️",
        color: "#3B82F6",
        perks: ["Leaderboard spotlight badge", "Squad creation access"],
    },
    {
        level: 4,
        name: "Sergeant",
        minScore: 350,
        badge: "🛡️",
        color: "#F59E0B",
        perks: ["Exclusive reward drops", "Early mission access"],
    },
    {
        level: 5,
        name: "Lieutenant",
        minScore: 700,
        badge: "⭐",
        color: "#8B5CF6",
        perks: ["Officer title", "Direct commander recognition", "War room insights"],
    },
    {
        level: 6,
        name: "Captain",
        minScore: 1200,
        badge: "🌟",
        color: "#EC4899",
        perks: ["All Lieutenant perks", "Co-lead mission launches", "Platoon management"],
    },
    {
        level: 7,
        name: "Major",
        minScore: 2000,
        badge: "💫",
        color: "#DC2626",
        perks: ["All Captain perks", "Strategic mission planning", "Annual leadership award eligibility"],
    },
    {
        level: 8,
        name: "General",
        minScore: 3500,
        badge: "👑",
        color: "#D4AF37",
        perks: ["All Major perks", "Supreme command authority", "Hall of fame entry", "Platform-wide recognition"],
    },
];
